"""The A2UI contract — owned by the official `a2ui-agent-sdk`, not by us.

WHY THIS EXISTS
---------------
We used to hand-roll every part of A2UI: a pydantic `A2UINode` mirroring the catalog, a
hand-written catalog description in the render skill, and a hand-written `_valid_a2ui_panel`
id-graph check in app.py. All three were re-implementations of things the A2UI project already
ships — and each could drift from the real spec without anyone noticing.

`a2ui-agent-sdk` gives us, from the SPEC ITSELF:
  * the **catalog + message schemas** (assets/0.8) — rendered into the agent's prompt, so the
    model is told the real component contract instead of our prose summary of it;
  * a **parser** that unwraps `<a2ui-json>` blocks and heals common LLM JSON damage
    (trailing commas, …);
  * a **validator** that rejects unknown components, bad enum values (`usageHint`), and
    dangling id references — the checks `_valid_a2ui_panel` approximated.

WHY VERSION 0.8
---------------
The console renders with `@a2ui/react@0.10`, whose wire messages are `surfaceUpdate` /
`beginRendering` carrying `{"id", "component": {...}}` components. That is exactly the SDK's
**0.8** asset set. So the agent now emits our REAL wire format directly — no envelope
translation anywhere. (0.9+ renamed the messages to updateComponents / createSurface and moved
to a `{"messageType": …}` envelope; adopting those means upgrading the frontend renderer too.)

WHO USES WHAT
-------------
  * ui_renderer agent (Agent Runtime) → `render_instruction()` — its system prompt.
  * app (Cloud Run) → `parse_panel()` + `rewrite_ids()` — validate the agent's A2UI, then slot
    it into the console surface (see agents/a2ui_surface.py).

NOT bundled: `catalogId`. The 0.8 `standard_catalog_definition.json` asset has no `catalogId`
key, so `A2uiCatalog.catalog_id` raises. Nothing here touches it — the 0.8 validator does not
need it, and we pass no `examples_path` (the only other caller). Do not add few-shot examples
via `CatalogConfig(examples_path=...)` without giving the catalog an id first.
"""

import os
from typing import Callable

# The components the console's renderer + our panel layout actually use. The catalog is PRUNED
# to these before it reaches the prompt and the validator, so the model cannot reach for a
# Button/Slider/Modal we have no interaction wiring for — and if it tries anyway, validation
# rejects it instead of the browser silently dropping an unrenderable component.
ALLOWED_COMPONENTS = ["Text", "Card", "Column", "Divider"]

# Likewise for messages: a panel is a surface, nothing else. No dataModelUpdate/deleteSurface.
ALLOWED_MESSAGES = ["beginRendering", "surfaceUpdate"]

_VERSION = "0.8"
_format = None


def _fmt():
    """The SDK format object (catalog + schemas + parser + prompt generator), built once.

    Lazy on purpose: this reads the SDK's bundled schema assets off disk, and it must not run
    at import time in the app — an import-time failure there would take down a service whose
    whole point is to degrade gracefully to `panels_fallback`.
    """
    global _format
    if _format is None:
        import a2ui
        from a2ui.inference_formats.direct_json import DirectJsonFormat
        from a2ui.schema.catalog import CatalogConfig
        from a2ui.schema.catalog_provider import FileSystemCatalogProvider

        catalog_def = os.path.join(
            a2ui.__path__[0], "assets", _VERSION, "standard_catalog_definition.json")
        _format = DirectJsonFormat(
            version=_VERSION,
            catalogs=[CatalogConfig(name="standard",
                                    provider=FileSystemCatalogProvider(catalog_def))])
    return _format


_catalog_cache = None


def _catalog():
    """The pruned catalog — the single source of truth for both prompt and validation.

    Cached: pruning copies the schemas, and the catalog lazily builds a jsonschema registry
    for its validator, so a fresh one per panel would rebuild that on every report.
    """
    global _catalog_cache
    if _catalog_cache is None:
        _catalog_cache = _fmt().get_selected_catalog(allowed_components=ALLOWED_COMPONENTS,
                                                     allowed_messages=ALLOWED_MESSAGES)
    return _catalog_cache


def render_instruction(role_description: str, ui_description: str = "") -> str:
    """The ui_renderer agent's system instruction, generated BY THE SDK.

    `role_description` (who the agent is + what it renders) and `ui_description` (the layout
    procedure) are ours; everything else — the response rules, the `<a2ui-json>` block
    contract, and the full component/message JSON schema — comes from the spec assets.

    `include_schema=True` is load-bearing. Without it the model gets no schema and improvises
    an envelope (`{"messageType": …}`, `{"messages": […]}`, …) that then fails to parse; with
    it, the emitted messages are the 0.8 wire format every time.
    """
    return _fmt().prompt_generator.generate(
        role_description=role_description,
        ui_description=ui_description,
        allowed_components=ALLOWED_COMPONENTS,
        allowed_messages=ALLOWED_MESSAGES,
        include_schema=True,
    )


def has_a2ui(text: str) -> bool:
    """True if the response carries an `<a2ui-json>` block (vs. the plain-JSON form task)."""
    from a2ui.schema.constants import A2UI_OPEN_TAG
    return A2UI_OPEN_TAG in (text or "")


def _unwrap_message(message):
    """Heal the ONE envelope slip we measured: a message emitted as a bare surfaceUpdate BODY.

    ~1 run in 10, the model drops the wrapper and emits `{"surfaceId", "components"}` directly
    instead of `{"surfaceUpdate": {"surfaceId", "components"}}`. The schema is unambiguous here
    — `components` appears in exactly one message type — so re-wrapping is safe and lossless,
    and the healed message still goes through full validation below. Anything else is passed
    through untouched, to be accepted or rejected on its merits.
    """
    if not isinstance(message, dict) or any(k in message for k in ALLOWED_MESSAGES):
        return message
    if "components" in message:
        return {"surfaceUpdate": message}
    if "root" in message:
        return {"beginRendering": message}
    return message


def _strict_messages(text: str) -> list:
    """Whole-response parse: unwrap the blocks, JSON-heal (trailing commas…), collect messages.

    Raises A2uiParseError when the response has no A2UI block, or when a block's JSON is
    damaged beyond what the fixer handles — `_recovered_messages` picks those up.
    """
    from a2ui.parser.payload_fixer import parse_and_fix

    messages = []
    for part in _fmt().parser.unwrap(text):
        if part.a2ui_raw:
            block = parse_and_fix(part.a2ui_raw)
            messages.extend(_unwrap_message(m)
                            for m in (block if isinstance(block, list) else [block]))
    return messages


def _recovered_messages(text: str) -> list:
    """The SDK's STREAMING parser, run over the finished response as one chunk.

    It exists to render a UI that is still arriving, so it closes what is open and yields each
    component as it completes — which also makes it the SDK's answer to a block the model
    closed wrong. Measured: ~1 run in 10 ends `…}}}]}` — one brace short of closing the
    surfaceUpdate — and a strict JSON parse loses the ENTIRE panel over that byte, while this
    path recovers every component. Whatever it yields is still validated by the caller.
    """
    from a2ui.inference_formats.direct_json.streaming import DirectJsonStreamParser

    messages = []
    for part in DirectJsonStreamParser(_catalog()).process_chunk(text):
        if part.a2ui_json:
            messages.extend(part.a2ui_json)
    return messages


def parse_panel(text: str) -> dict | None:
    """An agent response → one validated panel `{root, components}` in WIRE form, or None.

    Parse strictly, fall back to the streaming parser's recovery, then validate the result
    against the spec either way (invalid → raises, caller falls back to a rule-based panel).
    We then flatten the surfaceUpdate components and resolve the panel's root:
    `beginRendering.root` if the agent sent one, else the first component (the SDK's prompt
    rules require the root to come first).

    The returned components are A2UI wire components — `{"id", "component": {...}}` — ready to
    stream once their ids are namespaced into the console surface (`rewrite_ids`).
    """
    from a2ui.core import A2uiParseError

    try:
        messages = _strict_messages(text)
    except A2uiParseError:
        messages = _recovered_messages(text)
        if not messages:
            raise                                # nothing salvageable — report the real error
    _catalog().validator.validate(messages)

    components, root = [], None
    for message in messages:
        if isinstance(message.get("surfaceUpdate"), dict):
            components.extend(message["surfaceUpdate"].get("components") or [])
        if isinstance(message.get("beginRendering"), dict):
            root = message["beginRendering"].get("root") or root
    if not components:
        return None
    return {"root": root or components[0].get("id"), "components": components}


def _ref_fields():
    """{component name: (id-valued fields, id-list-valued fields)} — read off the CATALOG.

    This is how `rewrite_ids` knows that `Card.child` holds an id and `Column.children.
    explicitList` holds a list of ids, without us restating the catalog in code.
    """
    from a2ui.validation.validator import extract_component_ref_fields
    return extract_component_ref_fields(_catalog())


def rewrite_ids(components: list, nid: Callable[[str], str]) -> list:
    """Return `components` with every component id AND every id REFERENCE mapped through `nid`.

    Used to namespace a panel into a shared surface: the ids the agent invented are local to
    its own panel, so two panels would otherwise collide on `card`/`col`/`t1`. Which fields
    hold references is taken from the catalog (`_ref_fields`), so this stays correct if the
    allowed component set changes.
    """
    refs = _ref_fields()
    out = []
    for component in components:
        if not isinstance(component, dict):
            continue
        body = component.get("component")
        name = next(iter(body), None) if isinstance(body, dict) else None
        singles, lists = refs.get(name, (frozenset(), frozenset()))
        out.append({**component,
                    "id": nid(component.get("id", "")),
                    "component": {name: _rewrite_props(body[name], singles, lists, nid)}}
                   if name else component)
    return out


def _rewrite_props(props, singles, lists, nid):
    """Recursive half of `rewrite_ids` — walks a component's props, remapping ref-valued keys.

    Nesting matters: a Column's ids live at `children.explicitList`, not at the top level, so
    a flat pass over the props would miss them.
    """
    if not isinstance(props, dict):
        return props
    out = {}
    for key, value in props.items():
        if key in singles and isinstance(value, str):
            out[key] = nid(value)
        elif key in lists and isinstance(value, list):
            out[key] = [nid(v) if isinstance(v, str) else v for v in value]
        elif isinstance(value, dict):
            out[key] = _rewrite_props(value, singles, lists, nid)
        else:
            out[key] = value
    return out


def text_of(component: dict) -> str:
    """The literal string of a Text component (empty for any other component).

    Used by the app to reject a structurally-valid but CONTENT-EMPTY panel, which renders as an
    invisible card. That is a product judgement the spec has no opinion on, so it stays ours.
    """
    body = (component or {}).get("component")
    if not isinstance(body, dict) or "Text" not in body:
        return ""
    return ((body["Text"] or {}).get("text") or {}).get("literalString") or ""
